import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Modality, HarmCategory, HarmBlockThreshold, Type } from "@google/genai";

const app = express();
const PORT = 3000;

// Increase limit for base64 images
app.use(express.json({ limit: '50mb' }));

// Lazy initialize Gemini
let ai: any = null;
function getAI() {
  if (!ai) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    ai = new GoogleGenAI({ 
      apiKey,
      httpOptions: {
        headers: { 'User-Agent': 'aistudio-build' }
      }
    });
  }
  return ai;
}

const DEFAULT_MODEL = "gemini-3-flash-preview";

// Helper to handle Gemini responses
const handleGeminiResponse = (response: any) => {
    const candidate = response.candidates?.[0];
    if (!candidate) throw new Error('No content was generated by the model.');

    for (const part of candidate.content?.parts || []) {
        if (part.inlineData) {
            return {
                base64: part.inlineData.data,
                mimeType: part.inlineData.mimeType,
                name: 'generated-image.png',
            };
        }
    }
    
    if (candidate.finishReason && candidate.finishReason !== 'STOP') {
        throw new Error(`Generation failed due to safety settings: ${candidate.finishReason}`);
    }

    return { text: response.text };
};

// API Routes
app.post("/api/ai/generate-image", async (req, res) => {
    try {
        const { productImages, prompt, styleImages, aspectRatio = "1:1" } = req.body;
        const genAI = getAI();
        const parts: any[] = [];

        if (productImages && productImages.length > 0) {
            productImages.forEach((img: any) => parts.push({ inlineData: { data: img.base64, mimeType: img.mimeType } }));
        }
        parts.push({ text: prompt });
        if (styleImages && styleImages.length > 0) {
            styleImages.forEach((img: any) => parts.push({ inlineData: { data: img.base64, mimeType: img.mimeType } }));
        }

        const response = await genAI.models.generateContent({
            model: DEFAULT_MODEL,
            contents: { parts },
            config: {
                imageConfig: { aspectRatio },
            },
        });

        res.json(handleGeminiResponse(response));
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

app.post("/api/ai/analyze-image", async (req, res) => {
    try {
        const { images, instructions, type } = req.body;
        const genAI = getAI();
        const parts: any[] = images.map((img: any) => ({ inlineData: { data: img.base64, mimeType: img.mimeType } }));
        
        let prompt = instructions;
        if (type === 'style') {
            prompt = "Analyze the visual style of these images. Describe the lighting, color palette, mood, and aesthetic in detail for a text-to-image prompt.";
        } else if (type === 'logo') {
             prompt = "Analyze this logo and extract the primary brand colors. Return them as a JSON object with a 'colors' key containing a string array of hex codes.";
        }
        
        parts.push({ text: prompt });

        const response = await genAI.models.generateContent({
            model: DEFAULT_MODEL,
            contents: { parts },
            config: type === 'logo' ? { responseMimeType: "application/json" } : {} 
        });

        res.json({ text: response.text });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

app.post("/api/ai/text-action", async (req, res) => {
    try {
        const { text, action } = req.body;
        const genAI = getAI();
        
        let prompt = text;
        if (action === 'translate') {
            prompt = `Translate the following text to English, preserving any technical or descriptive nuances: "${text}"`;
        } else if (action === 'expand') {
            prompt = `Expand this idea into a detailed text-to-image prompt: "${text}"`;
        }

        const response = await genAI.models.generateContent({
            model: DEFAULT_MODEL,
            contents: prompt,
        });
        res.json({ text: response.text });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

app.post("/api/ai/generate-speech", async (req, res) => {
    try {
        const { text, styleInstructions, voiceName } = req.body;
        const genAI = getAI();
        const ttsModel = "gemini-3.1-flash-tts-preview";
        const prompt = `Speak the following text ${styleInstructions ? '(' + styleInstructions + ')' : ''}: ${text}`;

        const response = await genAI.models.generateContent({
            model: ttsModel,
            contents: [{ parts: [{ text: prompt }] }],
            config: {
                responseModalities: [Modality.AUDIO],
                speechConfig: {
                    voiceConfig: {
                        prebuiltVoiceConfig: { voiceName },
                    },
                },
            },
        });

        const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
        res.json({ base64: base64Audio, name: `voiceover-${Date.now()}.wav` });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

// Advanced Generation Routes (Marketing, Storyboard, etc.)
app.post("/api/ai/complex-generation", async (req, res) => {
    try {
        const { type, data } = req.body;
        const genAI = getAI();
        
        const parts: any[] = [];
        if (data.images) {
            data.images.forEach((img: any) => parts.push({ inlineData: { data: img.base64, mimeType: img.mimeType } }));
        }
        if (data.image) {
             parts.push({ inlineData: { data: data.image.base64, mimeType: data.image.mimeType } });
        }

        if (type === 'campaign') {
            const instruction = `Act as a professional Creative Director and Marketing Strategist. Target Market: ${data.targetMarket}. Goal: "${data.userPrompt}". Post in ${data.dialect}. Generate 9 unique campaign post ideas. Return JSON array.`;
            const response = await genAI.models.generateContent({
                model: DEFAULT_MODEL,
                contents: { parts: [...parts, { text: instruction }] },
                config: { responseMimeType: "application/json" }
            });
            return res.json({ result: response.text });
        } else if (type === 'storyboard') {
            const instruction = `Act as a cinematic Storyboard Director. Context: "${data.customInstructions}". Create a 9-scene storyboard sequence. Return JSON array.`;
            const response = await genAI.models.generateContent({
                model: DEFAULT_MODEL,
                contents: { parts: [...parts, { text: instruction }] },
                config: { responseMimeType: "application/json" }
            });
            return res.json({ result: response.text });
        } else if (type === 'ad-creative') {
             const instruction = `Act as a top-tier Direct Response Copywriter. Platform: ${data.platform}. Audience: ${data.targetAudience}. Generate 3 high-converting ad variations. Return JSON array.`;
             const response = await genAI.models.generateContent({
                model: DEFAULT_MODEL,
                contents: { parts: [...parts, { text: instruction }] },
                config: { responseMimeType: "application/json" }
            });
             return res.json({ result: response.text });
        } else if (type === 'marketing-analysis') {
            const context = data.brandData.type === 'existing' ? `Link: ${data.brandData.link}` : `Brand: ${data.brandData.name}, Specialty: ${data.brandData.specialty}`;
            const instruction = `Marketing report for ${context}. Language: ${data.language}. Return Markdown.`;
            const response = await genAI.models.generateContent({
                model: DEFAULT_MODEL,
                contents: instruction,
            });
            return res.json({ result: response.text });
        } else if (type === 'rotation') {
            const angles = ['front view', 'side view', 'top view', '45 degree angle'];
            const results = await Promise.all(angles.map(async angle => {
                const anglePrompt = `${data.prompt}. Shot from ${angle}. Professional commercial photography, clean studio background. STRICTLY PRESERVE original product details.`;
                const response = await genAI.models.generateContent({
                    model: DEFAULT_MODEL,
                    contents: { parts: [parts[0], { text: anglePrompt }] },
                    config: {
                        imageConfig: { aspectRatio: "1:1" }
                    }
                });
                try {
                    return handleGeminiResponse(response);
                } catch (e) {
                    return null;
                }
            }));
            return res.json({ result: JSON.stringify(results.filter(r => r !== null)) });
        } else if (type === 'scenarios' || type === 'social-drafts' || type === 'targeting') {
             let instruction = '';
             if (type === 'scenarios') instruction = `Based on this product analysis: "${data.analysis}", suggest 6 professional and creative commercial photography scenarios. Return JSON array.`;
             if (type === 'social-drafts') instruction = `Act as a Viral Social Media Manager. Brand Info: ${JSON.stringify(data.brandData)}. Language: ${data.language}. Generate 3 posts. Return JSON array.`;
             if (type === 'targeting') instruction = `Act as an expert Ad Targeting Strategist for ${data.platform}. Suggest 5 targeted segments. Return JSON array of strings.`;
             
             const response = await genAI.models.generateContent({
                model: DEFAULT_MODEL,
                contents: { parts: [...parts, { text: instruction }] },
                config: { responseMimeType: "application/json" }
            });
             return res.json({ result: response.text });
        }

        res.status(400).json({ error: "Unknown complex generation type" });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

app.post("/api/ai/chat", async (req, res) => {
    try {
        const { history } = req.body;
        const genAI = getAI();
        
        const systemPrompt = `You are Vora AI, a hyper-intelligent creative strategist...`;

        const chat = genAI.chats.create({
            model: DEFAULT_MODEL,
            config: { systemInstruction: systemPrompt }
        });

        // We need to send history separately or use the chat session
        const response = await chat.sendMessage({ 
            message: history[history.length - 1].text 
        });
        res.json({ text: response.text });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

// Vite middleware for development
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*all', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer().catch(err => {
  console.error("Failed to start server:", err);
  process.exit(1);
});
