
import React, { useEffect, useRef, useCallback } from 'react';
import { CreatorStudioProject, ImageFile } from '../types';
import { analyzeStyleImage, translateText, generateImage, editImage, generateProductRotation } from '../services/geminiService';
import { resizeImage } from '../utils';
import CustomizationPanel from './CustomizationPanel';
import ImageWorkspace from './ImageWorkspace';
import PromptEditor from './PromptEditor';
import HistoryPanel from './HistoryPanel';
import ResultDisplay from './ResultDisplay';

import EnvironmentPresets from './EnvironmentPresets';
import RotationGallery from './RotationGallery';

interface CreatorStudioProps {
  project: CreatorStudioProject;
  setProject: React.Dispatch<React.SetStateAction<CreatorStudioProject>>;
}

const CreatorStudio: React.FC<CreatorStudioProps> = React.memo(({
  project,
  setProject,
}) => {
  
  const translateTimeoutRef = useRef<number | null>(null);
  const translationRequestCounter = useRef(0);

  const updateActiveProjectState = useCallback((updater: (projectDraft: CreatorStudioProject) => void) => {
    setProject(currentProject => {
      if (!currentProject) return currentProject;
      const projectToUpdate = { ...currentProject };
      updater(projectToUpdate);
      return projectToUpdate;
    });
  }, [setProject]);

  const handleEnhancePrompt = useCallback(() => {
    if (!project || !project.prompt) return;
    const enhanceKeywords = ", masterpiece, extremely detailed, professional commercial photography, 8k resolution, cinematic lighting, sharp focus, hyper-realistic, photorealistic textures, award-winning industrial design photo, high-end production quality";
    if (project.prompt.includes("masterpiece")) return;
    
    updateActiveProjectState(p => {
        p.prompt = p.prompt + enhanceKeywords;
        p.isPromptAutoGenerated = false;
    });
  }, [project, updateActiveProjectState]);

  const handleApplyPreset = useCallback((preset: any) => {
    updateActiveProjectState(p => {
        const textConstraint = "STRICTLY PRESERVE all original text, labels, and branding. NO EXTRA generated text.";
        p.prompt = `Professional high-end commercial photo of the product in a ${preset.name} environment. ${preset.prompt} ${textConstraint}`;
        p.isPromptAutoGenerated = false;
    });
  }, [updateActiveProjectState]);

  const handleGenerate360 = useCallback(async () => {
    if (!project || (project.productImages || []).length === 0) return;
    updateActiveProjectState(p => { p.isGeneratingRotation = true; p.rotationImages = []; });
    try {
        const results = await generateProductRotation((project.productImages || [])[0], project.prompt || "A professional product photo");
        updateActiveProjectState(p => { p.rotationImages = results; });
    } catch (err) {
        console.error(err);
    } finally {
        updateActiveProjectState(p => { p.isGeneratingRotation = false; });
    }
  }, [project, updateActiveProjectState]);

  // Analyze style image
  useEffect(() => {
    if (project?.styleImages?.length > 0 && !project.styleDescription && !project.isAnalyzingStyle && !project.error) {
      const getStyleDescription = async () => {
        updateActiveProjectState(p => { 
          p.isAnalyzingStyle = true;
          p.error = null;
        });
        try {
          const description = await analyzeStyleImage(project.styleImages);
          updateActiveProjectState(p => { p.styleDescription = description; });
        } catch (err) {
          console.error(err);
          updateActiveProjectState(p => {
            p.error = err instanceof Error ? err.message : "Could not analyze the style image.";
            p.styleDescription = null;
          });
        } finally {
          updateActiveProjectState(p => { p.isAnalyzingStyle = false; });
        }
      };
      getStyleDescription();
    } else if (project?.styleImages?.length === 0 && project?.styleDescription) {
      updateActiveProjectState(p => { p.styleDescription = null; });
    }
  }, [
    project?.id,
    project?.styleImages, 
    project?.styleDescription,
    project?.isAnalyzingStyle,
    project?.error,
    updateActiveProjectState
  ]);

  // Auto-generate prompt - MODIFIED: only fills if empty and auto-mode is ON
  useEffect(() => {
    if (!project || !project.isPromptAutoGenerated) return;
    
    const productImages = project.productImages || [];
    const styleImages = project.styleImages || [];
    const options = project.options || { lightingStyle: 'Studio', cameraPerspective: 'Front' };
    const isAnalyzingStyle = !!project.isAnalyzingStyle;
    const styleDescription = project.styleDescription;
    
    if (productImages.length === 0 && styleImages.length === 0) {
      return;
    }

    let newPrompt = `Professional high-end commercial photograph`;
    if (productImages.length > 0) {
      newPrompt += ` of the subject from the provided image`;
    }
    
    newPrompt += `. 
 
Setting: Place the subject in a sophisticated and professional new environment that captures the essence, mood, and background aesthetic of the style reference. The background should be a high-quality reimagining inspired by the style reference, ensuring it complements the subject perfectly.
 
Key requirements:
- Lighting: ${options.lightingStyle} with professional studio quality.
- Perspective: ${options.cameraPerspective}.
- Mood: High-end, clean, and professional.
- Content Protection: STRICTLY PRESERVE all original text, labels, and branding on the product. DO NOT erase or modify existing writing. NO EXTRA generated text in the scene. 8k resolution, sharp focus, hyper-realistic.`;

    if (styleImages.length > 0) {
      if (isAnalyzingStyle) newPrompt += `\n- Visual Inspiration: Reimagining the reference style...`;
      else if (styleDescription) newPrompt += `\n- Background/Style Essence: ${styleDescription}. Create a similar professional atmosphere.`;
      else newPrompt += `\n- Background/Style Essence: Resembling the provided style reference atmosphere and lighting.`;
    }
    
    if(project.prompt === '') updateActiveProjectState(p => { p.prompt = newPrompt; });
  }, [
    project?.id,
    project?.isPromptAutoGenerated,
    project?.productImages, 
    project?.styleImages, 
    project?.options, 
    project?.isAnalyzingStyle, 
    project?.styleDescription,
    updateActiveProjectState
  ]);

  // Translation effect
  useEffect(() => {
    const arabicRegex = /[\u0600-\u06FF]/;
    if (!project || project.isPromptAutoGenerated) {
        if (project?.translatedPrompt || project?.isTranslating) {
            updateActiveProjectState(p => { p.translatedPrompt = null; p.isTranslating = false; });
        }
        return;
    }

    if (translateTimeoutRef.current) clearTimeout(translateTimeoutRef.current);
    const promptToTranslate = project.prompt;

    if (!arabicRegex.test(promptToTranslate) || !promptToTranslate.trim()) {
        if (project.translatedPrompt || project.isTranslating) {
            updateActiveProjectState(p => { p.translatedPrompt = null; p.isTranslating = false; });
        }
        return;
    }

    translateTimeoutRef.current = window.setTimeout(async () => {
        translationRequestCounter.current += 1;
        const currentRequestId = translationRequestCounter.current;
        updateActiveProjectState(p => { p.isTranslating = true; p.error = null; });

        try {
            const translated = await translateText(promptToTranslate);
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => { if (p.prompt === promptToTranslate) p.translatedPrompt = translated; });
            }
        } catch (err) {
            console.error(err);
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'Translation failed.'; });
            }
        } finally {
            if (translationRequestCounter.current === currentRequestId) {
                updateActiveProjectState(p => { p.isTranslating = false; });
            }
        }
    }, 700);
  }, [project?.prompt, project?.isPromptAutoGenerated, updateActiveProjectState]);
  
  const handleGenerate = useCallback(async () => {
    if (!project || !project.prompt) {
      updateActiveProjectState(p => { p.error = 'Please write a prompt or select a mode.'; });
      return;
    }
    const currentPrompt = project.prompt;
    updateActiveProjectState(p => { p.isLoading = true; p.error = null; p.generatedImage = null; });

    try {
      const result = await generateImage(project.productImages || [], project.prompt, project.styleImages || []);
      updateActiveProjectState(p => {
          p.generatedImage = result;
          p.history = [{ image: result, prompt: currentPrompt }, ...(p.history || [])];
      });
    } catch (err) {
      console.error(err);
      updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'Generation failed.'; });
    } finally {
      updateActiveProjectState(p => { p.isLoading = false; });
    }
  }, [project, updateActiveProjectState]);

  // Logic for Step 1: APPLY STOCK BASE
  const handleApplyStockBase = useCallback(() => {
    if (!project) return;
    const current = project.prompt?.trim() || '';
    const baseText = current && !current.includes("Stock photo") ? current : "the product";
    
    const updatedPrompt = `Stock photo of ${baseText}, pure white background, professional commercial photography, high-end studio lighting, sophisticated white rim lighting accents, 8k resolution, sharp focus, hyper-realistic, extremely high detail. STRICTLY PRESERVE original branding. NO EXTRA generated text.`;
    
    updateActiveProjectState(p => { 
        p.prompt = updatedPrompt; 
        p.isPromptAutoGenerated = false;
    });
  }, [project, updateActiveProjectState]);

  // NEW: Handle AI Vision Modes
  const handleApplyVisionMode = useCallback((mode: 'fusion' | 'placement') => {
    if (!project) return;
    const { styleDescription } = project;
    
    let updatedPrompt = '';
    const textConstraint = "STRICTLY PRESERVE all original text, labels, and branding. DO NOT modify existing writing. NO EXTRA generated text in the scene.";

    if (mode === 'fusion') {
        updatedPrompt = `Professional Style Fusion: Take the subject from the main image and seamlessly re-render it using the visual style, professional lighting, and artistic mood of the reference image. ${styleDescription ? `Reference context: ${styleDescription}.` : ''} High-end commercial quality, 8k resolution, photorealistic. ${textConstraint}`;
    } else {
        updatedPrompt = `Professional Scene Placement: Extract the subject from the main image and place it professionally into the exact environment, background, and spatial context of the reference image. ${styleDescription ? `Reference context: ${styleDescription}.` : ''} Match the lighting, shadows, and perspective of the reference perfectly for a hyper-realistic result. ${textConstraint}`;
    }
    
    updateActiveProjectState(p => { 
        p.prompt = updatedPrompt; 
        p.isPromptAutoGenerated = false;
    });
  }, [project, updateActiveProjectState]);

  // Logic for Step 2: CHANGE RIM COLOR
  const handleApplyRimColor = useCallback((color: string) => {
    if (!project) return;
    const current = project.prompt || '';
    
    if (current.includes("rim lighting")) {
        const regex = /(\w+)\s+rim lighting/;
        const updated = current.replace(regex, `${color} rim lighting`);
        updateActiveProjectState(p => { p.prompt = updated; });
    } else {
        updateActiveProjectState(p => { p.prompt = `${current} with ${color} rim lighting accents.`; });
    }
  }, [project, updateActiveProjectState]);

  const handleImageEdit = async (editPromptText: string) => {
    if (!project?.generatedImage) return;
    
    updateActiveProjectState(p => { p.isEditing = true; p.error = null; });
    try {
        const result = await editImage(project.generatedImage as ImageFile, editPromptText);
        updateActiveProjectState(p => {
            p.generatedImage = result;
            p.history = [{ image: result, prompt: editPromptText }, ...(p.history || [])];
        });
    } catch (err) {
        updateActiveProjectState(p => { p.error = err instanceof Error ? err.message : 'Edit failed'; });
    } finally {
        updateActiveProjectState(p => { p.isEditing = false; });
    }
  };


  const handleFileUpload = useCallback(async (files: File[], target: 'product' | 'style') => {
    if (!files || files.length === 0) return;
    updateActiveProjectState(p => { p.uploadingTarget = target; p.error = null; });
    let currentError: string | null = null;
    
    const filePromises = files.map(file => {
        return new Promise<ImageFile | null>(async (resolve) => {
            if (!file.type.startsWith('image/')) {
                if(!currentError) currentError = `File '${file.name}' not supported.`;
                resolve(null); return;
            }
            try {
                const resizedFile = await resizeImage(file, 2048, 2048);
                const reader = new FileReader();
                reader.onloadend = () => {
                    resolve({ base64: (reader.result as string).split(',')[1], mimeType: resizedFile.type, name: resizedFile.name });
                };
                reader.readAsDataURL(resizedFile);
            } catch (err) {
                resolve(null);
            }
        });
    });

    const resultsArr = await Promise.all(filePromises);
    const validImages = resultsArr.filter((img): img is ImageFile => img !== null);
    
    if (validImages.length > 0) {
        updateActiveProjectState(p => {
            if (target === 'product') {
                p.productImages = [...(p.productImages || []), ...validImages];
            } else {
                p.styleImages = [...(p.styleImages || []), ...validImages];
                p.styleDescription = null;
            }
        });
    }
    updateActiveProjectState(p => { p.error = currentError; p.uploadingTarget = null; });
  }, [updateActiveProjectState]);

  const onProductImagesUpload = useCallback((files: File[]) => handleFileUpload(files, 'product'), [handleFileUpload]);
  const onStyleImagesUpload = useCallback((files: File[]) => handleFileUpload(files, 'style'), [handleFileUpload]);

  const onProductImageRemove = useCallback((idx: number) => updateActiveProjectState(p => {
    p.productImages = (p.productImages || []).filter((_, i) => i !== idx);
  }), [updateActiveProjectState]);

  const onStyleImageRemove = useCallback((idx: number) => updateActiveProjectState(p => {
    p.styleImages = (p.styleImages || []).filter((_, i) => i !== idx);
    p.styleDescription = null;
  }), [updateActiveProjectState]);

  const onProductImageUpdate = useCallback((idx: number, img: ImageFile) => updateActiveProjectState(p => {
    if(p.productImages) p.productImages[idx] = img;
  }), [updateActiveProjectState]);

  const onStyleImageUpdate = useCallback((idx: number, img: ImageFile) => updateActiveProjectState(p => {
    if(p.styleImages) { p.styleImages[idx] = img; p.styleDescription = null; }
  }), [updateActiveProjectState]);
  
  const handleSetPrompt = (prompt: string) => updateActiveProjectState(p => {
    p.prompt = prompt;
    p.isPromptAutoGenerated = false;
  });

  if (!project) return null;

  return (
    <>
    <main id="creator-studio-main" className="w-full flex flex-col gap-10 pt-4 md:pt-8 pb-32 animate-in fade-in duration-1000 studio-container">
        {/* Premium Header */}
        <div className="flex flex-col md:flex-row justify-between items-end gap-6 mb-4 px-2 md:px-0">
            <div className="flex-1">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-[8px] font-black uppercase tracking-[0.4em] mb-4">
                    Neural Creative Engine v4.0
                </div>
                <h2 className="text-3xl md:text-5xl font-black text-white tracking-tighter font-display uppercase leading-none">
                    Creator Studio
                </h2>
                <p className="text-text-secondary text-sm md:text-base font-light mt-3 max-w-xl">
                    Harness the power of localized generative intelligence to synthesize studio-grade commercial imagery in real-time.
                </p>
            </div>
            <div className="flex items-center gap-4 hidden md:flex">
                <div className="flex flex-col items-end">
                    <span className="text-[10px] font-black text-accent uppercase tracking-widest">System Latency</span>
                    <span className="text-xs font-mono text-white/40">24ms (Optimized)</span>
                </div>
                <div className="w-10 h-10 rounded-full border border-white/5 bg-white/[0.02] flex items-center justify-center">
                    <div className="w-2 h-2 rounded-full bg-accent animate-ping"></div>
                </div>
            </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Left Column: Controls & AI Lab */}
            <div id="creator-studio-controls" className="lg:col-span-4 flex flex-col gap-8">
            <div id="uploaders-grid" className="flex flex-col gap-4">
                <div id="product-uploader-card" className="glass-card p-6 rounded-[2rem] flex flex-col gap-4 border border-white/5 relative group bg-white/[0.02]">
                    <div className="flex items-center justify-between px-2">
                      <h3 className="input-label !mb-0">Main Subject</h3>
                      <div className="w-2 h-2 rounded-full bg-accent animate-pulse"></div>
                    </div>
                    <ImageWorkspace
                        id="creator-product-uploader"
                        images={project.productImages || []}
                        onImagesUpload={onProductImagesUpload}
                        onImageRemove={onProductImageRemove}
                        isUploading={project.uploadingTarget === 'product'}
                        onImageUpdate={onProductImageUpdate}
                    />
                </div>
                
                <div id="style-uploader-card" className="glass-card p-6 rounded-[2rem] flex flex-col gap-4 border border-white/5 relative group bg-white/[0.02]">
                    <div className="flex items-center justify-between px-2">
                       <h3 className="input-label !mb-0">Style DNA</h3>
                       <div className="w-2 h-2 rounded-full bg-white/20"></div>
                    </div>
                    <ImageWorkspace 
                        id="creator-style-uploader"
                        title="Style"
                        images={project.styleImages || []}
                        onImagesUpload={onStyleImagesUpload}
                        onImageRemove={onStyleImageRemove}
                        isUploading={project.uploadingTarget === 'style'}
                        onImageUpdate={onStyleImageUpdate}
                    />
                </div>
            </div>

            <div id="ai-lab-container" className="glass-card p-6 rounded-[2rem] border border-white/5 flex flex-col gap-6 bg-white/[0.01]">
                <div className="flex items-center gap-3 px-2">
                  <div className="w-8 h-8 rounded-lg bg-accent/20 flex items-center justify-center text-accent">🧬</div>
                  <h3 id="ai-lab-title" className="input-label !mb-0">Creative Laboratory</h3>
                </div>

                <EnvironmentPresets 
                    id="environment-presets"
                    selectedId={null} 
                    onSelect={handleApplyPreset} 
                />
                
                <div id="ai-tools-grid-section" className="flex flex-col gap-3">
                    <div id="ai-tools-grid" className="grid grid-cols-2 gap-3">
                        <button 
                            id="enhance-ai-btn"
                            onClick={handleEnhancePrompt}
                            className="bg-white/5 hover:bg-white/10 border border-white/10 p-5 rounded-2xl flex flex-col items-center gap-3 transition-all active:scale-95 group"
                        >
                            <span className="text-2xl group-hover:scale-125 transition-transform">✨</span>
                            <span className="text-[9px] font-black uppercase tracking-widest text-text-secondary">Refine Focus</span>
                        </button>
                        <button 
                            id="style-fusion-btn"
                            onClick={() => handleApplyVisionMode('fusion')}
                            className="bg-white/5 hover:bg-white/10 border border-white/10 p-5 rounded-2xl flex flex-col items-center gap-3 transition-all active:scale-95 group"
                        >
                            <span className="text-2xl group-hover:scale-125 transition-transform">🎨</span>
                            <span className="text-[9px] font-black uppercase tracking-widest text-text-secondary">Style Transfer</span>
                        </button>
                    </div>
                </div>
            </div>

            <div className="glass-card p-6 rounded-[2rem] border border-white/5 flex flex-col gap-6 bg-white/[0.01]">
              <CustomizationPanel options={project.options} setOptions={(opt) => updateActiveProjectState(p => { p.options = opt; })} />
            </div>
        </div>

        {/* Center Column: Prompt & Generation */}
        <div className="lg:col-span-5 flex flex-col gap-8 order-2">
            <div className="glass-card rounded-[2.5rem] p-8 border border-white/5 shadow-2xl relative overflow-hidden flex flex-col min-h-[600px]">
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-accent to-transparent"></div>
                
                <ResultDisplay 
                    imageFile={project.generatedImage} 
                    isLoading={project.isLoading}
                    onEdit={handleImageEdit}
                    isEditing={project.isEditing}
                />

                <div className="mt-auto pt-8">
                  <PromptEditor
                      prompt={project.prompt}
                      setPrompt={handleSetPrompt}
                      isAutoGenerated={project.isPromptAutoGenerated}
                      onResetPrompt={() => updateActiveProjectState(p => { p.isPromptAutoGenerated = !p.isPromptAutoGenerated; })}
                      translatedPrompt={project.translatedPrompt}
                      isTranslating={project.isTranslating}
                      onUseTranslation={(t) => updateActiveProjectState(p => { p.prompt = t; p.isPromptAutoGenerated = false; p.translatedPrompt = null; })}
                      onApplyStockBase={handleApplyStockBase}
                      onApplyRimColor={handleApplyRimColor}
                      onApplyVisionMode={handleApplyVisionMode}
                  />

                  <button
                      id="main-generate-image-btn"
                      onClick={handleGenerate}
                      disabled={project.isLoading || !project.prompt || !!project.uploadingTarget}
                      className="w-full mt-6 bg-accent hover:bg-accent-dark text-white font-black py-6 rounded-3xl text-xl shadow-[0_20px_50px_rgba(var(--color-accent-rgb),0.3)] transition-all transform active:scale-95 disabled:opacity-50 disabled:transform-none uppercase tracking-[0.2em] font-display"
                  >
                      {project.isLoading ? (
                        <div className="flex items-center justify-center gap-3">
                          <div className="w-5 h-5 border-4 border-white/30 border-t-white rounded-full animate-spin"></div>
                          Visualizing...
                        </div>
                      ) : 'Generate Vision'}
                  </button>

                  {project.error && (
                    <div className="mt-4 bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-xl text-[10px] font-black text-center uppercase tracking-widest animate-in slide-in-from-top-2">
                      Error: {project.error}
                    </div>
                  )}
                </div>
            </div>
            
            {project.rotationImages?.length > 0 && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-700">
                    <RotationGallery images={project.rotationImages || []} isGenerating={!!project.isGeneratingRotation} />
                </div>
            )}
        </div>

        {/* Right Column: History & Utils */}
        <div className="lg:col-span-3 flex flex-col gap-6 order-3">
            <div className="glass-card p-6 rounded-[2rem] border border-white/5 bg-white/[0.01]">
              <div className="flex items-center justify-between mb-4">
                <h3 className="input-label !mb-0">Action Ledger</h3>
                <span className="text-[10px] text-accent font-black">{project.history?.length || 0} ITEMS</span>
              </div>
              <HistoryPanel history={project.history} onSelect={(img) => updateActiveProjectState(p => { p.generatedImage = img; })} />
            </div>

            <div className="glass-card p-6 rounded-[2rem] border border-white/5 bg-accent/5 overflow-hidden relative">
               <div className="absolute top-0 right-0 p-4 opacity-10">
                  <span className="text-4xl">🪄</span>
               </div>
               <h4 className="text-white font-black text-xs uppercase tracking-widest mb-2">Magic Spin</h4>
               <p className="text-text-secondary text-[11px] mb-4 leading-relaxed">Generate a 360° product rotation from your vision.</p>
               <button 
                  onClick={handleGenerate360}
                  disabled={project.isGeneratingRotation || (project.productImages || []).length === 0}
                  className="w-full py-3 rounded-xl bg-white/5 hover:bg-white/10 text-white text-[10px] font-black uppercase tracking-widest transition-all border border-white/10"
               >
                  {project.isGeneratingRotation ? 'Processing...' : 'Run Rotation (4-Angle)'}
               </button>
            </div>
        </div>
    </div>
</main>

{/* Status bar simulated element */}
<div className="fixed bottom-0 left-0 right-0 h-10 bg-black/80 backdrop-blur-xl border-t border-white/10 z-[100] flex items-center justify-between px-6 px-safe">
    <div className="flex items-center gap-4">
        <div className="flex items-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-accent animate-pulse"></div>
            <span className="text-[8px] font-black text-white/40 uppercase tracking-widest">Neural Link Active</span>
        </div>
        <div className="w-px h-3 bg-white/10"></div>
        <span className="text-[8px] font-black text-accent uppercase tracking-widest hidden sm:inline">Neural Creative Matrix</span>
    </div>
    <div className="flex items-center gap-4">
        <span className="text-[8px] font-black text-white/40 uppercase tracking-widest font-mono">LATENCY: 12MS</span>
        <div className="w-px h-3 bg-white/10"></div>
        <span className="text-[8px] font-black text-emerald-500 uppercase tracking-widest font-mono">SECURE</span>
    </div>
</div>
</>
  );
});

export default CreatorStudio;
